# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{devise_harvard_auth_proxy}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Collis-Puro"]
  s.date = %q{2011-07-08}
  s.description = %q{Harvard Auth Proxy module for Devise}
  s.email = %q{djcp@cyber.law.harvard.edu}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README"
  ]
  s.homepage = %q{http://github.com/berkmancenter/devise_harvard_auth_proxy}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Harvard Auth Proxy authentication module for Devise}
  s.test_files = [
    "test/devise_harvard_auth_proxy.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<devise>, ["~> 1.4.0"])
    else
      s.add_dependency(%q<devise>, ["~> 1.4.0"])
    end
  else
    s.add_dependency(%q<devise>, ["~> 1.4.0"])
  end
end

